"""shorts-lab twice-daily monitor syncs — two no-agent hermes cron jobs.

Separate crons, created the moment the matching monitor exists:
  shorts-lab-ads-sync     ads for monitored pages   (0 */12, on the hour)
  shorts-lab-shorts-sync  competitor shorts         (30 */12, staggered)

``no_agent``: each generated script under ~/.hermes/scripts/ runs with
zero LLM cost, stays silent (empty stdout = no delivery), and records
results in the plugin kv for the dashboard.
"""
from __future__ import annotations

import logging
from pathlib import Path

try:
    from . import store
except ImportError:  # loaded outside package context (tests, tooling)
    import store  # type: ignore

logger = logging.getLogger(__name__)

_HEADER = '''#!/usr/bin/env python3
"""Generated by the shorts-lab plugin — twice-daily {what} sync.

Hermes no-agent cron job. Empty stdout keeps the run silent; results
land in the plugin kv.
"""
import importlib
import importlib.util
import sys
import time
from pathlib import Path

PLUGIN_ROOT = {plugin_root!r}
PKG = "hermes_plugin_pkg_shorts_lab"

if PKG not in sys.modules:
    spec = importlib.util.spec_from_file_location(
        PKG, str(Path(PLUGIN_ROOT) / "__init__.py"),
        submodule_search_locations=[PLUGIN_ROOT])
    mod = importlib.util.module_from_spec(spec)
    sys.modules[PKG] = mod
    spec.loader.exec_module(mod)

store = importlib.import_module(PKG + ".store")
'''

_ADS_BODY = '''meta_ads = importlib.import_module(PKG + ".meta_ads")

result = {"at": time.time()}
if store.list_ad_pages() and meta_ads.get_ads_source() != "none":
    try:
        result["summary"] = meta_ads.sync_all_pages()
    except Exception as exc:
        result["error"] = str(exc)[:200]
else:
    result["skipped"] = "no monitored pages or no ads backend connected"
store.kv_set("cronAdsSync", result)
# stdout intentionally empty -> silent cron delivery
'''

_SHORTS_BODY = '''transcripts = importlib.import_module(PKG + ".transcripts")

result = {"at": time.time()}
if store.list_channels():
    try:
        result["summary"] = transcripts.fetch_shorts()
    except Exception as exc:
        result["error"] = str(exc)[:200]
else:
    result["skipped"] = "no channels tracked"
store.kv_set("cronShortsSync", result)
# stdout intentionally empty -> silent cron delivery
'''

JOBS = {
    "ads": {
        "name": "shorts-lab-ads-sync",
        "script": "shorts-lab-ads-sync.py",
        "schedule": "0 */12 * * *",
        "body": _ADS_BODY,
        "what": "monitored-ads",
    },
    "shorts": {
        "name": "shorts-lab-shorts-sync",
        "script": "shorts-lab-shorts-sync.py",
        "schedule": "30 */12 * * *",
        "body": _SHORTS_BODY,
        "what": "competitor-shorts",
    },
}


def _write_script(kind: str) -> Path:
    spec = JOBS[kind]
    scripts_dir = store._home() / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    path = scripts_dir / spec["script"]
    path.write_text(
        _HEADER.format(what=spec["what"],
                       plugin_root=str(Path(__file__).resolve().parent))
        + spec["body"])
    return path


def ensure_job(kind: str) -> dict:
    """Create (or repair) one of the twice-daily sync jobs. Idempotent —
    called whenever the matching monitor is added."""
    from cron import jobs as cron_jobs

    spec = JOBS[kind]
    _write_script(kind)
    saved = store.kv_get(f"cronJob:{kind}") or {}

    job = None
    if saved.get("jobId"):
        job = cron_jobs.resolve_job_ref(saved["jobId"])
    if job is None:
        job = cron_jobs.resolve_job_ref(spec["name"])

    if job is None:
        job = cron_jobs.create_job(
            prompt=None, schedule=spec["schedule"], name=spec["name"],
            deliver="local", script=spec["script"], no_agent=True)
        logger.info("shorts-lab: created %s job %s", spec["name"], job["id"])
    else:
        cron_jobs.update_job(job["id"], {
            "schedule": spec["schedule"],
            "script": spec["script"],
            "no_agent": True,
            "enabled": True,
        })
    store.kv_set(f"cronJob:{kind}",
                 {"jobId": job["id"], "schedule": spec["schedule"]})
    return {"jobId": job["id"], "schedule": spec["schedule"]}


def is_enabled() -> bool:
    """Auto-sync is OPT-IN — off until the user flips the page toggle."""
    return bool(store.kv_get("cronSyncEnabled"))


def set_enabled(enabled: bool) -> dict:
    """Flip both crons together. Enabling ensures both jobs (their scripts
    no-op safely when a monitor type has nothing to sync); disabling turns
    existing jobs off in place."""
    store.kv_set("cronSyncEnabled", bool(enabled))
    if enabled:
        for kind in JOBS:
            ensure_job(kind)
        return {"enabled": True}
    try:
        from cron import jobs as cron_jobs
        for kind, spec in JOBS.items():
            saved = store.kv_get(f"cronJob:{kind}") or {}
            job = None
            if saved.get("jobId"):
                job = cron_jobs.resolve_job_ref(saved["jobId"])
            if job is None:
                job = cron_jobs.resolve_job_ref(spec["name"])
            if job is not None:
                cron_jobs.update_job(job["id"], {"enabled": False})
    except Exception:  # noqa: BLE001 — cron absent outside hermes
        pass
    return {"enabled": False}


def ensure_ads_job() -> dict:
    return ensure_job("ads")


def ensure_shorts_job() -> dict:
    return ensure_job("shorts")
